export interface ShortcutData {
  id: string;
  title: string;
  shortcut: string;
  description: string;
  category: string;
  platform: string;
}

export const PLATFORMS = [
  {
    id: 'phpstorm',
    name: 'PHPStorm',
    icon: 'fab fa-php',
    description:
      'Essential keyboard shortcuts for efficient PHPStorm development',
  },
  {
    id: 'archlinux',
    name: 'Arch Linux',
    icon: 'fab fa-linux',
    description: 'Essential terminal and system shortcuts for Arch Linux',
  },
  {
    id: 'ubuntu',
    name: 'Ubuntu',
    icon: 'fab fa-ubuntu',
    description: 'Essential keyboard shortcuts and commands for Ubuntu',
  },
  {
    id: 'git',
    name: 'Git',
    icon: 'fab fa-git',
    description: 'Essential Git commands for version control and collaboration',
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: 'fab fa-docker',
    description:
      'Essential Docker commands for container management and development',
  },
  {
    id: 'vim',
    name: 'Vim',
    icon: 'fas fa-terminal',
    description:
      'Essential keyboard shortcuts for efficient text editing in Vim',
  },
];

export const CATEGORIES = [
  { id: 'navigation', name: 'Navigation', color: 'bg-blue-100 text-blue-800' },
  { id: 'editing', name: 'Editing', color: 'bg-green-100 text-green-800' },
  { id: 'debugging', name: 'Debugging', color: 'bg-red-100 text-red-800' },
  { id: 'system', name: 'System', color: 'bg-purple-100 text-purple-800' },
  {
    id: 'window',
    name: 'Window Management',
    color: 'bg-yellow-100 text-yellow-800',
  },
];

export const SHORTCUTS_DATA: ShortcutData[] = [
  // PHPStorm shortcuts
  {
    id: 'phpstorm-quick-open',
    title: 'Quick Open File',
    shortcut: 'Ctrl+Shift+N',
    description: 'Quickly open any file in your project',
    category: 'navigation',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-go-declaration',
    title: 'Go to Declaration',
    shortcut: 'Ctrl+B',
    description: 'Navigate to the declaration of a symbol',
    category: 'navigation',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-find-files',
    title: 'Find in Files',
    shortcut: 'Ctrl+Shift+F',
    description: 'Search for text across all project files',
    category: 'navigation',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-recent-files',
    title: 'Recent Files',
    shortcut: 'Ctrl+E',
    description: 'Show recently opened files',
    category: 'navigation',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-duplicate-line',
    title: 'Duplicate Line',
    shortcut: 'Ctrl+D',
    description: 'Duplicate the current line or selection',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-multiple-cursors',
    title: 'Multiple Cursors',
    shortcut: 'Alt+Click',
    description: 'Add multiple cursors for simultaneous editing',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-comment-line',
    title: 'Comment Line',
    shortcut: 'Ctrl+/',
    description: 'Toggle line comment',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-reformat-code',
    title: 'Reformat Code',
    shortcut: 'Ctrl+Alt+L',
    description: 'Automatically format code according to style settings',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-toggle-breakpoint',
    title: 'Toggle Breakpoint',
    shortcut: 'Ctrl+F8',
    description: 'Toggle breakpoint at current line',
    category: 'debugging',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-step-over',
    title: 'Step Over',
    shortcut: 'F8',
    description: 'Step over to the next line in debugging',
    category: 'debugging',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-step-into',
    title: 'Step Into',
    shortcut: 'F7',
    description: 'Step into function calls during debugging',
    category: 'debugging',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-resume-program',
    title: 'Resume Program',
    shortcut: 'F9',
    description: 'Continue program execution',
    category: 'debugging',
    platform: 'phpstorm',
  },

  // Arch Linux shortcuts
  {
    id: 'arch-package-update',
    title: 'Package Update',
    shortcut: 'sudo pacman -Syu',
    description: 'Update all installed packages',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-install-package',
    title: 'Install Package',
    shortcut: 'sudo pacman -S [package]',
    description: 'Install a specific package',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-remove-package',
    title: 'Remove Package',
    shortcut: 'sudo pacman -R [package]',
    description: 'Remove a package',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-search-package',
    title: 'Search Package',
    shortcut: 'pacman -Ss [query]',
    description: 'Search for packages in repositories',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-open-terminal',
    title: 'Open Terminal',
    shortcut: 'Ctrl+Alt+T',
    description: 'Open a new terminal window',
    category: 'window',
    platform: 'archlinux',
  },
  {
    id: 'arch-switch-desktop',
    title: 'Switch Desktop',
    shortcut: 'Ctrl+Alt+Arrow',
    description: 'Switch between virtual desktops',
    category: 'window',
    platform: 'archlinux',
  },
  {
    id: 'arch-directory-nav',
    title: 'Directory Navigation',
    shortcut: 'cd ..',
    description: 'Go up one directory level',
    category: 'navigation',
    platform: 'archlinux',
  },
  {
    id: 'arch-list-files',
    title: 'List Files',
    shortcut: 'ls -la',
    description: 'List all files with detailed information',
    category: 'navigation',
    platform: 'archlinux',
  },

  // Ubuntu shortcuts
  {
    id: 'ubuntu-update-system',
    title: 'Update System',
    shortcut: 'sudo apt update && sudo apt upgrade',
    description: 'Update package list and upgrade all packages',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-install-package',
    title: 'Install Package',
    shortcut: 'sudo apt install [package]',
    description: 'Install a specific package',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-remove-package',
    title: 'Remove Package',
    shortcut: 'sudo apt remove [package]',
    description: 'Remove a package',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-search-package',
    title: 'Search Package',
    shortcut: 'apt search [query]',
    description: 'Search for packages in repositories',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-show-applications',
    title: 'Show Applications',
    shortcut: 'Super',
    description: 'Open activities overview and application launcher',
    category: 'window',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-switch-windows',
    title: 'Switch Windows',
    shortcut: 'Alt+Tab',
    description: 'Switch between open applications',
    category: 'window',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-lock-screen',
    title: 'Lock Screen',
    shortcut: 'Super+L',
    description: 'Lock the screen',
    category: 'window',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-take-screenshot',
    title: 'Take Screenshot',
    shortcut: 'PrtScr',
    description: 'Take a screenshot of the entire screen',
    category: 'window',
    platform: 'ubuntu',
  },
  {
    id: 'git-status',
    title: 'Check Status',
    shortcut: 'git status',
    description: 'Show the working tree status',
    category: 'system',
    platform: 'git',
  },
  {
    id: 'git-add',
    title: 'Stage File',
    shortcut: 'git add [file]',
    description: 'Add file contents to the index (stage for commit)',
    category: 'system',
    platform: 'git',
  },
  {
    id: 'git-commit',
    title: 'Commit Changes',
    shortcut: 'git commit -m "message"',
    description: 'Record changes to the repository',
    category: 'system',
    platform: 'git',
  },
  {
    id: 'git-push',
    title: 'Push Changes',
    shortcut: 'git push',
    description: 'Upload local repository content to remote',
    category: 'system',
    platform: 'git',
  },
  {
    id: 'git-pull',
    title: 'Pull Changes',
    shortcut: 'git pull',
    description: 'Fetch from and integrate with another repository or branch',
    category: 'system',
    platform: 'git',
  },
  {
    id: 'git-branch',
    title: 'List Branches',
    shortcut: 'git branch',
    description: 'List all local branches',
    category: 'navigation',
    platform: 'git',
  },
  {
    id: 'git-checkout',
    title: 'Switch Branch',
    shortcut: 'git checkout [branch]',
    description: 'Switch to specified branch',
    category: 'navigation',
    platform: 'git',
  },
  {
    id: 'docker-list-containers',
    title: 'List Containers',
    shortcut: 'docker ps -a',
    description: 'List all containers',
    category: 'system',
    platform: 'docker',
  },
  {
    id: 'docker-run',
    title: 'Run Container',
    shortcut: 'docker run [image]',
    description: 'Run a container from an image',
    category: 'system',
    platform: 'docker',
  },
  {
    id: 'docker-build',
    title: 'Build Image',
    shortcut: 'docker build -t [name] .',
    description: 'Build a Docker image from Dockerfile',
    category: 'editing',
    platform: 'docker',
  },
  {
    id: 'docker-stop',
    title: 'Stop Container',
    shortcut: 'docker stop [container]',
    description: 'Stop a running container',
    category: 'system',
    platform: 'docker',
  },
  {
    id: 'docker-remove-container',
    title: 'Remove Container',
    shortcut: 'docker rm [container]',
    description: 'Remove a stopped container',
    category: 'system',
    platform: 'docker',
  },
  {
    id: 'docker-exec',
    title: 'Access Container',
    shortcut: 'docker exec -it [container] bash',
    description: 'Open a bash shell in a running container',
    category: 'window',
    platform: 'docker',
  },
  {
    id: 'vim-insert-mode',
    title: 'Enter Insert Mode',
    shortcut: 'i',
    description: 'Switch from normal to insert mode',
    category: 'editing',
    platform: 'vim',
  },
  {
    id: 'vim-save',
    title: 'Save File',
    shortcut: ':w',
    description: 'Write (save) the file',
    category: 'editing',
    platform: 'vim',
  },
  {
    id: 'vim-quit',
    title: 'Quit Vim',
    shortcut: ':q',
    description: 'Quit Vim',
    category: 'system',
    platform: 'vim',
  },
  {
    id: 'vim-save-and-quit',
    title: 'Save and Quit',
    shortcut: ':wq',
    description: 'Save file and exit Vim',
    category: 'system',
    platform: 'vim',
  },
  {
    id: 'vim-delete-line',
    title: 'Delete Line',
    shortcut: 'dd',
    description: 'Delete the current line',
    category: 'editing',
    platform: 'vim',
  },
  {
    id: 'vim-visual-mode',
    title: 'Enter Visual Mode',
    shortcut: 'v',
    description: 'Select text character-wise',
    category: 'editing',
    platform: 'vim',
  },
  {
    id: 'vim-copy',
    title: 'Copy Selection',
    shortcut: 'y',
    description: 'Yank (copy) selected text',
    category: 'editing',
    platform: 'vim',
  },
  {
    id: 'vim-paste',
    title: 'Paste Text',
    shortcut: 'p',
    description: 'Paste yanked text',
    category: 'editing',
    platform: 'vim',
  },
  {
    id: 'phpstorm-go-to-line',
    title: 'Go to Line',
    shortcut: 'Ctrl+G',
    description: 'Navigate to a specific line number',
    category: 'navigation',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-go-to-symbol',
    title: 'Go to Symbol',
    shortcut: 'Ctrl+Alt+Shift+N',
    description: 'Navigate to a symbol in the project',
    category: 'navigation',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-refactor-this',
    title: 'Refactor This',
    shortcut: 'Ctrl+Alt+Shift+T',
    description: 'Open refactoring options for selected code',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-move-line-up',
    title: 'Move Line Up',
    shortcut: 'Shift+Alt+Up',
    description: 'Move current line up',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-extend-selection',
    title: 'Extend Selection',
    shortcut: 'Ctrl+W',
    description: 'Select code block by block',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-shrink-selection',
    title: 'Shrink Selection',
    shortcut: 'Ctrl+Shift+W',
    description: 'Shrink selected code block',
    category: 'editing',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-evaluate-expression',
    title: 'Evaluate Expression',
    shortcut: 'Alt+F8',
    description: 'Evaluate code while debugging',
    category: 'debugging',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-run-to-cursor',
    title: 'Run to Cursor',
    shortcut: 'Alt+F9',
    description: 'Run code until it reaches cursor position',
    category: 'debugging',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-find-action',
    title: 'Find Action',
    shortcut: 'Ctrl+Shift+A',
    description: 'Search and execute any IDE action',
    category: 'system',
    platform: 'phpstorm',
  },
  {
    id: 'phpstorm-toggle-terminal',
    title: 'Toggle Terminal',
    shortcut: 'Alt+F12',
    description: 'Open or close the integrated terminal',
    category: 'system',
    platform: 'phpstorm',
  },
  {
    id: 'ubuntu-show-desktop',
    title: 'Show Desktop',
    shortcut: 'Ctrl+Super+D',
    description: 'Minimize all windows and show desktop',
    category: 'window',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-new-terminal-tab',
    title: 'New Terminal Tab',
    shortcut: 'Ctrl+Shift+T',
    description: 'Open a new tab in terminal',
    category: 'window',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-kill-app',
    title: 'Force Close App',
    shortcut: 'xkill',
    description: 'Click on a window to force it to close',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-open-settings',
    title: 'Open Settings',
    shortcut: 'Super + ,',
    description: 'Open system settings',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'ubuntu-monitor-resources',
    title: 'Monitor Resources',
    shortcut: 'gnome-system-monitor',
    description: 'Launch system monitor to check CPU, RAM usage',
    category: 'system',
    platform: 'ubuntu',
  },
  {
    id: 'arch-show-disk-usage',
    title: 'Show Disk Usage',
    shortcut: 'df -h',
    description: 'Show mounted partitions and disk usage',
    category: 'navigation',
    platform: 'archlinux',
  },
  {
    id: 'arch-disk-usage-directory',
    title: 'Disk Usage by Directory',
    shortcut: 'du -sh *',
    description: 'Show size of each file and directory',
    category: 'navigation',
    platform: 'archlinux',
  },
  {
    id: 'arch-memory-usage',
    title: 'Check Memory Usage',
    shortcut: 'free -h',
    description: 'Show available and used memory',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-list-processes',
    title: 'List Processes',
    shortcut: 'ps aux | less',
    description: 'Display all running processes',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-reboot',
    title: 'Reboot System',
    shortcut: 'sudo reboot',
    description: 'Reboot the machine',
    category: 'system',
    platform: 'archlinux',
  },
  {
    id: 'arch-xrandr-resolution',
    title: 'Change Display Resolution',
    shortcut: 'xrandr --output HDMI-1 --mode 1920x1080',
    description: 'Set display resolution using xrandr',
    category: 'window',
    platform: 'archlinux',
  },
];

export const getCategoryColor = (category: string): string => {
  const categoryData = CATEGORIES.find((cat) => cat.id === category);
  return categoryData?.color || 'bg-gray-100 text-gray-800';
};

export const getPlatformData = (platformId: string) => {
  return PLATFORMS.find((platform) => platform.id === platformId);
};

export const getShortcutsByPlatform = (platform: string): ShortcutData[] => {
  return SHORTCUTS_DATA.filter((shortcut) => shortcut.platform === platform);
};

export const getShortcutsByCategory = (category: string): ShortcutData[] => {
  return SHORTCUTS_DATA.filter((shortcut) => shortcut.category === category);
};

export const searchShortcuts = (query: string): ShortcutData[] => {
  const searchTerm = query.toLowerCase();
  return SHORTCUTS_DATA.filter(
    (shortcut) =>
      shortcut.title.toLowerCase().includes(searchTerm) ||
      shortcut.description.toLowerCase().includes(searchTerm) ||
      shortcut.shortcut.toLowerCase().includes(searchTerm),
  );
};
