name: react-project-build
kind: pipeline
type: docker

trigger:
  event:
    - push
    - pull_request

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    commands:
      - git clone https://$GITHUB_TOKEN@github.com/$DRONE_REPO ./$PROJECT_NAME
      - cd ./$PROJECT_NAME
      - git checkout $DRONE_COMMIT

  - name: install-deps
    image: node:20-alpine
    commands:
      - cd ./$PROJECT_NAME
      - npm run ci

  - name: build
    image: node:20-alpine
    commands:
      - cd ./$PROJECT_NAME
      - npm run ci
      - npm run build

---

name: react-project-promote
kind: pipeline
type: docker

trigger:
  event:
    - promote

steps:
  - name: production
    image: appleboy/drone-ssh
    when:
      target:
        - production
    settings:
      host:
        from_secret: docker_host
      username:
        from_secret: username_ssh
      password:
        from_secret: password_ssh
      port: 22
      command_timeout: 2m
      script:
        - |
          if [ ! -d "/var/www/${DRONE_REPO_NAME}-${DRONE_DEPLOY_TO}" ]; then
              git clone https://${GITHUB_TOKEN}@github.com/${DRONE_REPO} /var/www/${DRONE_REPO_NAME}-${DRONE_DEPLOY_TO}
          fi
        - cd /var/www/${DRONE_REPO_NAME}-${DRONE_DEPLOY_TO}
        - git fetch
        - git reset --hard origin/${DRONE_BRANCH}
        - git checkout ${DRONE_BRANCH}
        - git pull origin ${DRONE_BRANCH}
        - docker compose build
        - docker compose down
        - docker compose up -d --force-recreate